# Generated by Django 4.2.3 on 2023-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordertbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.CharField(max_length=500, null=True)),
                ('Code', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=20)),
                ('Aprice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
            ],
        ),
    ]
