# Generated by Django 4.2.3 on 2023-07-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertbl',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
