# Generated by Django 4.2.3 on 2023-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ordertbl_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertbl',
            name='Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
