# Generated by Django 4.2.3 on 2023-07-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ordertbl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertbl',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
