# Generated by Django 4.2.3 on 2023-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_ordertbl_amount_alter_ordertbl_aprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertbl',
            name='discount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordertbl',
            name='Amount',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordertbl',
            name='Aprice',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordertbl',
            name='Code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordertbl',
            name='Content',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertbl',
            name='ProductName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
