# Generated by Django 4.2.3 on 2023-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_ordertbl_discount_alter_ordertbl_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OD', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('NetTotal', models.CharField(max_length=10)),
                ('Discount', models.CharField(max_length=10)),
                ('SubTotal', models.CharField(max_length=10)),
                ('Round', models.CharField(max_length=10)),
                ('overAll', models.CharField(max_length=10)),
                ('mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=10)),
                ('ProductName', models.CharField(max_length=100)),
                ('Qty', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('Total', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
